on:
  schedule:
    - cron:  '5 4 * * *'
  workflow_dispatch:

permissions:
  packages: write

jobs:
  # Clean up all left-over docker images after tags have been moved to new builds
  remove-untagged:
    runs-on: ubuntu-latest
    steps:
      - name: Delete all images from repository without tags
        uses: Chizkiyahu/delete-untagged-ghcr-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository_owner: ${{ github.repository_owner }}
          repository: strowk/tisq
          package_name: tisq
          untagged_only: true
          owner_type: user
          except_untagged_multiplatform: true
